### ISSUE TITLE
need more docs on settings up swarm slaves

### ISSUE THREAD

**Issue by kenyee** [blacklabelops/jenkins#10]
I got this far:
- log into master via https (http if you didn't specify the keystore info) at port 8090
- use the initial key found in your server log to create an admin user
- create a swarm slave user and password
- edit your jenkins-slave.env file (SWARM_JENKINS_USER and SWARM_JENKINS_PASSWORD) to use the user/password for the swarm slave user you just created; leave SWARM_MASTER_URL blank so that the slaves use autodiscovery to find the master via UDP
- ctrl-c docker to stop it and do "docker-compose up" to restart it

but then the logs keep saying:

```
slave_1    | INFO: Retrying request
slave_1    | Aug 01, 2016 2:28:51 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
slave_1    | INFO: I/O exception (org.apache.commons.httpclient.NoHttpResponseException) caught when processing request: The server jenkins failed to respond
slave_1    | Aug 01, 2016 2:28:51 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
slave_1    | INFO: Retrying request
slave_1    | org.apache.commons.httpclient.NoHttpResponseException: The server jenkins failed to respond
slave_1    |    at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1976)

```

but at least they don't say this any more if you didn't put that info in:
`slave_1    | WARNING: Required credentials not available for BASIC <any realm>@jenkins:8080
`

**Comment by kenyee** [comment]
Another clue:
bash-4.2# java -jar swarm-client-jar-with-dependencies.jar 
Discovering Jenkins master

Found 1 eligible Jenkins.
Connecting to https://192.168.99.100:8090/
Failed to connect to https://192.168.99.100:8090/
javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative names present
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)

This led me to adding 
SWARM_CLIENT_PARAMETERS=-disableSslVerification

to the slave env file.
I also had to add - "50000:50000" to the ports list in docker compose for the master because if you use docker toolbox on the mac, swarm autodiscovery finds the public IP address of 192.168.99.100 instead of using the internal network IP of 172.18.0.2 to reach the jenkins server.
You can probably change SWARM_MASTER_URL to be http://jenkins:8090 instead.

Hope this helps someone...

**Comment by blacklabelops** [comment]
My example is still running fine:

```
$ curl -O https://raw.githubusercontent.com/blacklabelops/jenkins/master/docker-compose.yml
$ curl -O https://raw.githubusercontent.com/blacklabelops/jenkins/master/jenkins-master.env
$ curl -O https://raw.githubusercontent.com/blacklabelops/jenkins/master/jenkins-slave.env
$ docker-compose up -d
```
1. Take key from logs
2. Add admin user
3. Edit  jenkins-slave.env file (SWARM_JENKINS_USER and SWARM_JENKINS_PASSWORD)

```
$ docker-compose up -d
```

Result: Running jenkins and slave connects.

**Comment by kenyee** [comment]
I was trying to enable SSL on the Jenkins master machine.  So I set up JENKINS_KEYSTORE_PASSWORD and JENKINS_CERTIFICATE_DNAME in the jenkins-master.env to enable autogeneration of an SSL key.

jenkins 2.16 is also out BTW :-)
also, minor suggestion: for the swarm-jdk8, the Android SDK needs this, but I'll use yours as a base:

# Install Deps and build-essential

RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y --force-yes ca-certificates nano rsync sudo zip git build-essential wget libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5 lib32z1 python curl psmisc module-init-tools && \
    apt-get clean

**Comment by blacklabelops** [comment]
1. -disableSslVerification is standard inside my Jenkins slaves. You do not have to add it.
2. There is not UDP discovery inside my swarm-slave, standard master is http://jenkins:8080, because usually inside Docker the access Jenkins URL and internal Docker network url differs.
3. If you use SSL then you need to explicitly set jenkins master to https.
4. You do not have to expose port 50000 when you use a Docker network or links to connect.

**Comment by kenyee** [comment]
how do you do (3)?  It seemed to set itself up for https when I set those env variables?  I could no longer connect to http://192.168.99.100:8090...I had to use https://192.168.99.100:8090.

**Comment by blacklabelops** [comment]
Jenkins 2.16 will be available in 20 minutes (if the build succeeds).

**Comment by blacklabelops** [comment]
Examples: https://github.com/blacklabelops/jenkins-swarm

Master:

```
$ docker network create jenkinsnet
$ docker run -d --name jenkins --net jenkinsnet \
    -e "JENKINS_KEYSTORE_PASSWORD=swordfish" \
    -e "JENKINS_CERTIFICATE_DNAME=CN=SBleul,OU=Blacklabelops,O=blacklabelops.net,L=Munich,S=Bavaria,C=DE" \
    -p 8090:8080 \
    blacklabelops/jenkins
```

Slave:

```
$ docker run \
   --net jenkinsnet \
    -e "SWARM_MASTER_URL=https://jenkins:8080/" \
    blacklabelops/jenkins-swarm
```

**Comment by kenyee** [comment]
I was missing this in the sample jenkins-slave.env file which is the key part I missed:
SWARM_MASTER_URL=https://jenkins:8080/
also took out the disableSsl switch in the same file, and also the port 50000 line in docker-compose and it still works. Thanks :-)

**Comment by blacklabelops** [comment]
My swarm slaves are based on centos, no apt-get available.

**Comment by blacklabelops** [comment]
I am no Android developer so I can't test the slave. You can either send a pull-request with thos packages or.
1. Extend the image with your packages
2. Commit to Github repo
3. Add auto build on dockerhub
4. Add auto build each time when blacklabelops/swarm is build.

A voila, always fresh and updated!

**Comment by kenyee** [comment]
thanks...will do :-)
