### ISSUE TITLE
No plugins installed on a new Jenkins instance

### ISSUE THREAD

**Issue by rajcheval** [blacklabelops/jenkins#15]
We had a need to install specific version of plugins.
We followed the documentation and attempted to stand up a new jenkins using this command:

docker run --name jenkins -e "JENKINS_PLUGINS=gitlab-plugin hipchat:2.1.0 swarm" -p 8090:8080  blacklabelops/jenkins --debug=9

Jenkins came up but when I went to Jenkins UI, went to manage plugins, installed plugin I did not see any plugins installed.

I assumed that adding :version number of the plugin was the problem so I ran

docker run --name jenkins -e "JENKINS_PLUGINS=gitlab-plugin hipchat swarm" -p 8090:8080  blacklabelops/jenkins --debug=9

Even after running this command I do not see any plugins installed.

Finally I ran this command:

docker run --name jenkins  -p 8090:8080  blacklabelops/jenkins --debug=9

Even in this case I don't see any plugins installed.

Can you let us know how we can specify a list of plugins and their version via command line?

Thanks

**Comment by blacklabelops** [comment]
Due to the fast software development cycles from the Jenkins crew some features break from time to time. I will have to check for myself what's happening in the latest version.

**Comment by rajcheval** [comment]
Thank you for your help. We have been using your jenkins image for the past few months and it has been working well.

**Comment by blacklabelops** [comment]
I tried with the latest image `blacklabelops/jenkins:latest`.

Doing a brand new install. `hipchat:2.1.0` will not be installed but `hipchat` works. That means, that the specified version does not work with the Jenkins version.

I can see everything in logs:

Fail

~~~~
INFO: Checking hipchat:2.1.0
Mar 14, 2018 3:59:48 PM java.util.logging.LogManager$RootLogger log
INFO: Looking UpdateCenter for hipchat:2.1.0
Mar 14, 2018 3:59:48 PM java.util.logging.LogManager$RootLogger log
INFO: Checking swarm
~~~~

Success

~~~~
INFO: Checking hipchat
Mar 14, 2018 4:07:52 PM java.util.logging.LogManager$RootLogger log
INFO: Looking UpdateCenter for hipchat
Mar 14, 2018 4:07:52 PM java.util.logging.LogManager$RootLogger log
INFO: Installing hipchat
~~~~

Used command:

~~~~
docker run --name jenkins -e "JENKINS_PLUGINS=gitlab-plugin hipchat swarm" -p 8090:8080 blacklabelops/jenkins
~~~~

**Comment by rajcheval** [comment]
are you running your container on mac os? I am doing this on macbook pro. 
I just ran this command and I don't see any plugins installed.
See the details logs:

MacBook-Pro:~ rajindersingh$ docker run --name jenkins -e "JENKINS_PLUGINS=gitlab-plugin hipchat swarm" -p 8090:8080  blacklabelops/jenkins:latest --debug=9
Unable to find image 'blacklabelops/jenkins:latest' locally
latest: Pulling from blacklabelops/jenkins
ff3a5c916c92: Already exists 
89da71374447: Pull complete 
6b22ae133bd3: Pull complete 
ffdde01e4e37: Pull complete 
82082d822605: Pull complete 
ad9b511ed449: Pull complete 
f256a48ab925: Pull complete 
Digest: sha256:97acda66f41045fed12460ad19d93c4329cd39330abc93e24746eb93d6c2f92f
Status: Downloaded newer image for blacklabelops/jenkins:latest
+ set -o errexit
+++ dirname /home/jenkins/docker-entrypoint.sh
++ cd /home/jenkins
++ pwd
+ readonly CUR_DIR=/home/jenkins
+ CUR_DIR=/home/jenkins
+ source /home/jenkins/clicreation.sh
++ PARAMETER_TOKEN='"$@"'
++ ENVIRONMENT_VARIABLE_TOKEN='${JENKINS_CLI_URL}'
++ ENVIRONMENT_VARIABLE_SSH_TOKEN='${JENKINS_CLI_SSH}'
++ cat
++ cat
+ source /home/jenkins/initsecuritysettings.sh
++ '[' '!' -d /jenkins/init.groovy.d ']'
++ mkdir /jenkins/init.groovy.d
++ cat
+ '[' -n '' ']'
+ '[' -n '' ']'
+ java_vm_parameters=-Xmx512m
+ jenkins_parameters=
+ '[' false = true ']'
+ '[' -n '' ']'
+ '[' --debug=9 = jenkins ']'
+ [[ --debug=9 == \-\-* ]]
+ exec /usr/bin/java -Dfile.encoding=UTF-8 -Djenkins.install.runSetupWizard=false -Xmx512m -jar /usr/bin/jenkins/jenkins.war --debug=9
Running from: /usr/bin/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Mar 14, 2018 4:29:29 PM Main deleteWinstoneTempContents
WARNING: Failed to delete the temporary Winstone file /tmp/winstone/jenkins.war
Mar 14, 2018 4:29:29 PM org.eclipse.jetty.util.log.Log initialized
INFO: Logging initialized @480ms to org.eclipse.jetty.util.log.JavaUtilLog
Mar 14, 2018 4:29:29 PM winstone.Logger logInternal
INFO: Beginning extraction from war file
Mar 14, 2018 4:29:30 PM org.eclipse.jetty.server.handler.ContextHandler setContextPath
WARNING: Empty contextPath
Mar 14, 2018 4:29:30 PM org.eclipse.jetty.server.Server doStart
INFO: jetty-9.4.z-SNAPSHOT
Mar 14, 2018 4:29:30 PM org.eclipse.jetty.webapp.StandardDescriptorProcessor visitServlet
INFO: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
Mar 14, 2018 4:29:31 PM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart
INFO: DefaultSessionIdManager workerName=node0
Mar 14, 2018 4:29:31 PM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart
INFO: No SessionScavenger set, using defaults
Mar 14, 2018 4:29:31 PM org.eclipse.jetty.server.session.HouseKeeper startScavenging
INFO: Scavenging every 660000ms
Jenkins home directory: /jenkins found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
Mar 14, 2018 4:29:31 PM org.eclipse.jetty.server.handler.ContextHandler doStart
INFO: Started w.@6e9319f{/,file:///jenkins/war/,AVAILABLE}{/jenkins/war}
Mar 14, 2018 4:29:31 PM org.eclipse.jetty.server.AbstractConnector doStart
INFO: Started ServerConnector@62923ee6{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
Mar 14, 2018 4:29:31 PM org.eclipse.jetty.server.Server doStart
INFO: Started @2876ms
Mar 14, 2018 4:29:31 PM winstone.Logger logInternal
INFO: Winstone Servlet Engine v4.0 running: controlPort=disabled
Mar 14, 2018 4:29:32 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
Mar 14, 2018 4:29:32 PM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
Mar 14, 2018 4:29:34 PM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Mar 14, 2018 4:29:34 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
Mar 14, 2018 4:29:34 PM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Mar 14, 2018 4:29:34 PM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
Mar 14, 2018 4:29:35 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Started Download metadata
Mar 14, 2018 4:29:35 PM jenkins.util.groovy.GroovyHookScript execute
INFO: Executing /jenkins/init.groovy.d/securitySettings.groovy
Mar 14, 2018 4:29:35 PM java.util.logging.LogManager$RootLogger log
INFO: Security Settings
Mar 14, 2018 4:29:35 PM jenkins.InitReactorRunner$1 onAttained
INFO: Completed initialization
Mar 14, 2018 4:29:35 PM hudson.WebAppMain$3 run
INFO: Jenkins is fully up and running
Mar 14, 2018 4:29:37 PM hudson.model.UpdateSite updateData
INFO: Obtained the latest update center data file for UpdateSource default
Mar 14, 2018 4:29:37 PM hudson.model.DownloadService$Downloadable load
INFO: Obtained the updated data file for hudson.tasks.Maven.MavenInstaller
Mar 14, 2018 4:29:38 PM hudson.model.DownloadService$Downloadable load
INFO: Obtained the updated data file for hudson.tools.JDKInstaller
Mar 14, 2018 4:29:38 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Finished Download metadata. 3,077 ms

**Comment by rajcheval** [comment]
It turns out that adding --debug=9  does not install the plugins.

Based on your comment above it seems that I can specify the version of plugin and it will install correctly as long as it is compatible with the version of Jenkins.

Am I correct?

**Comment by rajcheval** [comment]
I found that if I specify the version number for a plugin it is not installed.
This happens even if plugin is compatible with Jenkins version.

docker run --name jenkins2 -e "JENKINS_PLUGINS=gitlab-plugin hipchat:2.1.1 swarm azure-ad:0.2.0 " -p 8090:8080  blacklabelops/jenkins:latest

In my example hipchat 2.1.1 is the latest version and is compatible with Jenkins.

https://gist.github.com/rajcheval/81fc90f09854fd813473065307612750

If I remove version_number hipchat plugin gets installed.

**Comment by blacklabelops** [comment]
I will recheck this, version numbers should work!

**Comment by blacklabelops** [comment]
This fixes your issue that there are no installation scripts running when you pass parameters, e.g. `--debug=9`.

**Comment by blacklabelops** [comment]
Here it is documented, that the Jenkins Update Center only allows to install the latest version of a plugin: https://jenkins.io/doc/book/managing/plugins/

I am using the update center for my plugin install. Very handy because it automatically also installs all dependencies. So apparently the version feature, e.g. `hipchat:2.1.1` does not work anymore.

If you want a specific version of a plugin there is, according to the article, only the `Advanced installation` routine left. Which means you have to download and install the plugin files by yourself manually.

**Comment by blacklabelops** [comment]
I have found an appropriate script in the official jenkins image: https://github.com/jenkinsci/docker/blob/master/install-plugins.sh

Maybe it is better to switch to the official one for you.

**Comment by rajcheval** [comment]
Steffen,

Thank you for your help today. I appreciate it. We will either incorporate a new script into your image or start using the official image.

Raj
