### ISSUE TITLE
Need to unset JENKINS_ADMIN_PASSWORD in docker-entrypoint.sh

### ISSUE THREAD

**Issue by gaborcsardi** [blacklabelops/jenkins#6]
Otherwise all jobs will have access to it. So you need to add 

``` sh
unset JENKINS_ADMIN_USER
unset JENKINS_ADMIN_PASSWORD
```

when you don't need them any more. Unless I am missing something....

Thanks for the project, btw.!

**Comment by blacklabelops** [comment]
Thanks for the idea! I will include this in the following days!
