### ISSUE TITLE
Support docker commands?

### ISSUE THREAD

**Issue by uptownhr** [blacklabelops/jenkins#9]
I've tried building my app and running docker containers from a jenkins install from docker before and ran into a few problems. Have any thought been put into your jenkins build?

**Comment by blacklabelops** [comment]
Please state your problems.

**Comment by blacklabelops** [comment]
This repository is a Jenkins Master without Docker, especially Docker dind. It's purpose is solely being a master. Job execution and tools installation is done by swarm slaves. App building and execution and Docker commands should be done by Jenkins (Swarm) Slaves.
